### PR TITLE
Add astra support

### LINKED ISSUE #5: Switch CIL to use non-GPU projection operator

### PR DESCRIPTION
**Pull request by nabriis**
Closes #5

### CODE REVIEW

**Comment by nabriis** [comment]
Hi @jakobsj, Can you test this branch this on a non-GPU device in a new conda environment via:
``` bash
conda install -c conda-forge -c intel -c astra-toolbox -c ccpi cil=22.1.0 astra-toolbox
pip install -e .
```

**Review by jakobsj — COMMENTED** [review]
Nice check for gpu, defaulting to cpu if possible. I wonder if tigre shouldn't be the first choice in case a gpu is available?

**Comment by nabriis** [comment]
> Nice check for gpu, defaulting to cpu if possible. I wonder if tigre shouldn't be the first choice in case a gpu is available?

It could be I guess. Is tigre a better choice?

**Comment by jakobsj** [comment]
TIGRE is more tightly integrated and generally used as default in CIL,
possibly faster too and clearer which projector/backprojector
implementations are used, so I would prefer this as the default.

**Review by jakobsj — APPROVED** [review]
Nice!

**Pull request merged**
