### PR TITLE
Bump minimum python version, test on latest python and update maintainer list

### PR DESCRIPTION
**Pull request by nabriis**
See https://github.com/CUQI-DTU/CUQIpy/issues/304

### CODE REVIEW

**Comment by jakobsj** [comment]
For 3.10, it appears to be a conda timeout issue.  We've seen long resolving times recently with conda. One solution that has worked for me has been to split in two, so can you try either 

conda create --name cil -c conda-forge -c intel -c ccpi cil=23.1.0
conda activate cil
conda install -c conda-forge -c ccpi astra-toolbox tigre ccpi-regulariser tomophantom "ipywidgets<8" ipython ipykernel

which has worked for me, or the stripped down

conda create --name cil -c conda-forge -c intel -c ccpi cil=23.1.0
conda activate cil
conda install -c conda-forge -c ccpi astra-toolbox 

and run again?  I'll look into what happened for 3.9, 3.11 and 3.12.

**Comment by jakobsj** [comment]
I see there is a new release of conda which should be a lot faster, maybe worth a try?
https://conda.org/blog/2023-11-06-conda-23-10-0-release/

**Comment by jakobsj** [comment]
For python 3.9, looking through the log, it appears to be an issue with numba, called by arviz, in lines 83 and 163 of the log.

**Comment by jakobsj** [comment]
I've been in touch with knowledgeable members of the CIL team who advised that CIL currently is only available through conda up to python 3.10 (https://github.com/TomographicImaging/CIL/blob/72404e6bb82e70ed0b61ebcf52477597878db06b/recipe/conda_build_config.yaml#L22-L34)  There are numba/astra issues at versions after that, this is being looked into but unclear when will be a available for later python versions.    One option is to manually build CIL from source (https://github.com/TomographicImaging/CIL#building-cil-from-source-code)  but I was warned there were guarantees it would work nicely with astra.   Could we simply remove building CUQIpy-CIL for 3.11 and 3.12?

**Comment by nabriis** [comment]
Hey @jakobsj. Updated now. Removed Python 3.9 aswell as 3.11, 3.12 testing. 3.9 seems to have an issue with numba after installing arviz post CIL update. If users run into an issue there it can be looked into.

**Review by jakobsj — APPROVED** [review]
Sounds like a good solution for now.

**Pull request merged**
